### ISSUE TITLE
Error occurs if element is temporarily not clickable

### ISSUE THREAD

**Issue by matdavies** [LiquidThinking/Xenon#53]
For example:

<pre>
Test(s) failed. OpenQA.Selenium.WebDriverException : Unexpected error. Element is not clickable at point (920.38330078125, 363.3999938964844). Other element would receive the click: <div currentmembers="" ng-if="!dataLoaded" class="overlay ng-binding"></div>
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at Xenon.Selenium.SeleniumXenonElement.Click()
   at Xenon.BaseXenonTest`1.<>c__DisplayClass7_0.<Click>b__0(IXenonBrowser browser)
   at Xenon.BaseXenonTest`1.RunTask(Action`1 task, AssertionFunc preWait, AssertionFunc postWait)
   at Xenon.BaseXenonTest`1.Click(String cssSelector, AssertionFunc customPreWait, AssertionFunc customPostWait)
   at Spawtz.Classes.Acceptance.Tests.Admin.MembershipTypes.CurrentMemberTests.CurrentMembersListPage_CancelMembership() in D:\Spawtz\Src\Spawtz.Classes.Acceptance.Tests\Admin\MembershipTypes\CurrentMemberTests.cs:line 20
« Hide stacktrace

</pre>

**Comment by jrote1** [comment]
Fixed in https://github.com/LiquidThinking/Xenon/commit/ef3564094dbe51a78a01cc63258fd98c44481062
